import { Rubik } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import Navbar from "./components/Navbar";

const rubik = Rubik({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${rubik.className} relative h-screen bg-blue-100 w-full flex justify-center border-blue-950 shadow-slate-700`}>
        <div className="w-4/5 ">
          <Navbar  />
          {children}
        </div>
      </body>
    </html>
  );
}
